# Generated by Django 4.2.3 on 2023-07-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
